export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_TOPIC = 'SET_TOPIC'
export const SET_COINTYPE = 'SET_COINTYPE'
export const SET_MARKETCOINTOCNY = 'SET_MARKETCOINTOCNY'

// 代理商
export const SET_AGENT_LOGIN_STATUS = 'SET_AGENT_LOGIN_STATUS'
export const SET_AGENT_TOKEN = 'SET_AGENT_TOKEN'
export const SET_AGENTINFO = 'SET_AGENTINFO'
export const SET_RECHARGE_LIMIT = 'SET_RECHARGE_LIMIT'
export const SET_WITHDRAW_LIMIT = 'SET_WITHDRAW_LIMIT'
