export const region = [
  {number: 'China', region: '86'},
  {number: 'Albania', region: '355'},
  {number: 'Andorra', region: '376'},
  {number: 'Austria', region: '43'},
  {number: 'Australia', region: '61'},
  {number: 'Algeria', region: '213'},
  {number: 'Angola', region: '244'},
  {number: 'Argentina', region: '54'},
  {number: 'Antigua and Barbuda', region: '1268'},
  {number: 'Afghanistan', region: '93'},
  {number: 'Azerbaijan', region: '994'},
  {number: 'Alaska(U.S.A)', region: '1907'},
  {number: 'Armenia', region: '374'},
  {number: 'Anguilla I.', region: '1264'},
  {number: 'Aruba I.', region: '297'},
  {number: 'Ascension', region: '247'},
  {number: 'Belarus', region: '375'},
  {number: 'Bulgaria', region: '359'},
  {number: 'Belgium', region: '32'},
  {number: 'Bosnia', region: '387'},
  {number: 'Benin', region: '229'},
  {number: 'Botswana', region: '267'},
  {number: 'Burkina Faso', region: '226'},
  {number: 'Burundi', region: '257'},
  {number: 'Barbados', region: '1246'},
  {number: 'Brazil', region: '55'},
  {number: 'Bolivia', region: '591'},
  {number: 'Belize', region: '501'},
  {number: 'Bahrain', region: '973'},
  {number: 'Bhutan', region: '975'},
  {number: 'Bangladesh', region: '880'},
  {number: 'Brunei Darussalam', region: '673'},
  {number: 'Bermuda Is.', region: '1441'},
  {number: 'Bosnia And Herzegovina', region: '387'},
  {number: 'Czech', region: '420'},
  {number: 'Croatia', region: '383'},
  {number: 'Cook Islands', region: '682'},
  {number: 'Cape Verde', region: '238'},
  {number: 'Congo', region: '242'},
  {number: 'Cameroon', region: '237'},
  {number: 'Comoro', region: '269'},
  {number: 'Chad', region: '235'},
  {number: 'Central Africa', region: '236'},
  {number: 'Commonwealth of The Bahamas', region: '1809'},
  {number: 'Colombia', region: '57'},
  {number: 'Costa Rica', region: '506'},
  {number: 'Cuba', region: '53'},
  {number: 'Canada', region: '1'},
  {number: 'Chile', region: '56'},
  {number: 'Cyprus', region: '357'},

  {number: 'Canaries Is.', region: '34'},
  {number: 'Cayman Is.', region: '1345'},
  {number: 'Christmas I.', region: '619164'},
  {number: 'Cocos I.', region: '619162'},
  {number: 'Commonwealth of Dominica', region: '1809'},
  {number: 'Cook IS.', region: '682'},
  {number: 'Denmark', region: '45'},
  {number: 'Djibouti', region: '253'},
  {number: 'Dominica', region: '1767'},
  {number: 'Dominican Republic', region: '809'},
  {number: 'Diego Garcia I.', region: '246'},
  {number: 'Estonia', region: '372'},
  {number: 'Egypt', region: '20'},
  {number: 'Ethiopia', region: '251'},
  {number: 'Equatorial Guinea', region: '240'},
  {number: 'Eritrea', region: '291'},
  {number: 'Ecuador', region: '593'},
  {number: 'El Salvador', region: '503'},
  {number: 'France', region: '33'},
  {number: 'Finland', region: '358'},
  {number: 'Fiji', region: '679'},
  {number: 'Falkland Is.', region: '500'},
  {number: 'Faroe Is.', region: '298'},
  {number: 'French Guiana', region: '594'},
  {number: 'French Polynesia', region: '689'},
  {number: 'Germany', region: '49'},
  {number: 'Greece', region: '30'},
  {number: 'Gambia', region: '220'},
  {number: 'Guinea', region: '224'},
  {number: 'Guinea-Bissau', region: '245'},
  {number: 'Ghana', region: '233'},
  {number: 'Gabon', region: '241'},
  {number: 'Grenada', region: '1809'},
  {number: 'Guyana', region: '592'},
  {number: 'Guatemala', region: '502'},
  {number: 'Georgia', region: '995'},
  {number: 'Gibraltar', region: '350'},
  {number: 'Greenland', region: '299'},
  {number: 'Guadeloupe I.', region: '590'},
  {number: 'Guam', region: '671'},
  {number: 'Hungary', region: '36'},
  {number: 'Haiti', region: '509'},
  {number: 'Honduras', region: '504'},
  {number: 'Hawaii', region: '1808'},
  {number: 'Ireland', region: '353'},
  {number: 'Iceland', region: '354'},
  {number: 'Italy', region: '39'},
  {number: 'Ivory Coast', region: '225'},
  {number: 'Iraq', region: '964'},
  {number: 'Iran', region: '98'},
  {number: 'Israel', region: '972'},
  {number: 'India', region: '91'},
  {number: 'Indonesia', region: '62'},
  {number: 'Jamaica', region: '1876'},
  {number: 'Japan', region: '81'},
  {number: 'Jordan', region: '962'},
  {number: 'Kiribati', region: '686'},
  {number: 'Kenya', region: '254'},
  {number: 'Korea(dpr of)', region: '85'},
  {number: 'Kazakhstan', region: '7'},
  {number: 'Korea(republic of)', region: '82'},
  {number: 'Kyrgyzstan', region: '996'},
  {number: 'Kampuchea', region: '855'},
  {number: 'Kuwait', region: '965'},
  {number: 'Latvia', region: '371'},
  {number: 'Lithuania', region: '370'},
  {number: 'Liechtenstein', region: '41'},
  {number: 'Luxembourg', region: '352'},
  {number: 'Lesotho', region: '266'},
  {number: 'Liberia', region: '231'},
  {number: 'Libya', region: '218'},
  {number: 'Laos', region: '856'},
  {number: 'Lebanon', region: '961'},
  {number: 'Malta', region: '356'},
  {number: 'Macedonia', region: '389'},
  {number: 'Moldova', region: '373'},
  {number: 'Monaco', region: '377'},
  {number: 'Marshall Is.', region: '692'},
  {number: 'Micronesia', region: '691'},
  {number: 'Madagascar', region: '261'},
  {number: 'Malawi', region: '265'},
  {number: 'Mali', region: '223'},
  {number: 'Mauritius', region: '230'},
  {number: 'Mauritania', region: '222'},
  {number: 'Morocco', region: '212'},
  {number: 'Mozambique', region: '258'},
  {number: 'Mexico', region: '52'},
  {number: 'Macao', region: '853'},
  {number: 'Maldive', region: '960'},
  {number: 'Malaysia', region: '60'},
  {number: 'Mongolia', region: '976'},
  {number: 'Myanmar', region: '95'},
  {number: 'Mariana Is.', region: '670'},
  {number: 'Martinique', region: '596'},
  {number: 'Mayotte I.', region: '269'},
  {number: 'Micronesia', region: '691'},
  {number: 'Midway I.', region: '1808'},
  {number: 'Montserrat I.', region: '1664'},
  {number: 'Netherlands', region: '31'},
  {number: 'Norway', region: '47'},
  {number: 'Nauru', region: '674'},
  {number: 'New Zealand', region: '64'},
  {number: 'Namibia', region: '264'},
  {number: 'Niger', region: '227'},
  {number: 'Nigeria', region: '234'},
  {number: 'Nicaragua', region: '505'},
  {number: 'Nepal', region: '977'},
  {number: 'Netherlandsantilles Is.', region: '599'},
  {number: 'New Caledonia Is.', region: '687'},
  {number: 'Niue I.', region: '683'},
  {number: 'Norfolk I,', region: '6723'},
  {number: 'Oman', region: '968'},
  {number: 'Poland', region: '48'},
  {number: 'Portugal', region: '351'},
  {number: 'Papua New Guinea', region: '675'},
  {number: 'Palau', region: '680'},
  {number: 'Paraguay', region: '595'},
  {number: 'Panama', region: '507'},
  {number: 'Peru', region: '51'},
  {number: 'Pakistan', region: '92'},
  {number: 'Palestinian', region: '930'},
  {number: 'Philippines', region: '63'},
  {number: 'Palau', region: '680'},
  {number: 'Puerto Rico', region: '1787'},
  {number: 'Qatar', region: '974'},
  {number: 'Russia', region: '7'},
  {number: 'Romania', region: '40'},
  {number: 'Rwanda', region: '250'},
  {number: 'Reunion I.', region: '262'},
  {number: 'Serbia', region: '381'},
  {number: 'Sweden', region: '46'},
  {number: 'Switzerland', region: '41'},
  {number: 'San Marino', region: '378'},
  {number: 'Slovak', region: '421'},
  {number: 'Slovenia', region: '386'},
  {number: 'Spain', region: '34'},
  {number: 'Samoa', region: '685'},
  {number: 'Solomon Is.', region: '677'},
  {number: 'South Africa', region: '27'},
  {number: 'Sierra Leone', region: '232'},
  {number: 'Senegal', region: '221'},
  {number: 'Seychelles', region: '248'},
  {number: 'San.Tome And Principe', region: '239'},
  {number: 'Swaziland', region: '268'},
  {number: 'Sudan', region: '249'},
  {number: 'Somali', region: '252'},
  {number: 'St.Christopher and Nevis', region: '1809'},
  {number: 'St.Lucia', region: '1758'},
  {number: 'Saint Vincent and the Grenadines', region: '1784'},
  {number: 'Suriname', region: '597'},
  {number: 'Saudi Arabia', region: '966'},
  {number: 'Sri Lanka', region: '94'},
  {number: 'Singapore', region: '65'},
  {number: 'Syria', region: '963'},
  {number: 'Samoa,Eastern', region: '684'},
  {number: 'Samoa,Western', region: '685'},
  {number: 'San.Marino', region: '378'},
  {number: 'San.Pierre And Miquelon I.', region: '508'},
  {number: 'St.Christopher and Nevis', region: '1809'},
  {number: 'St.Helena', region: '290'},
  {number: 'St.Vincent I.', region: '1784'},
  {number: 'Tonga', region: '676'},
  {number: 'Tuvalu', region: '688'},
  {number: 'Togo', region: '228'},
  {number: 'The Democratic Republic of Congo', region: '243'},
  {number: 'Tanzania', region: '255'},
  {number: 'Tunisia', region: '216'},
  {number: 'Trinidad and Tobago', region: '1809'},
  {number: 'The United Arab Emirates', region: '971'},
  {number: 'Timor Leste', region: '670'},
  {number: 'Tajikistan', region: '992'},
  {number: 'Thailand', region: '66'},
  {number: 'Turkey', region: '90'},
  {number: 'Turkmenistan', region: '993'},
  {number: 'Tokelau Is.', region: '690'},
  {number: 'Turks and Caicos Is.', region: '1809'},
  {number: 'Ukraine', region: '380'},
  {number: 'United Kingdom', region: '44'},
  {number: 'Uganda', region: '256'},
  {number: 'U.S.A', region: '1'},
  {number: 'Uruguay', region: '598'},
  {number: 'Uzbekistan', region: '998'},
  {number: 'Vatican', region: '379'},
  {number: 'Vanuatu', region: '678'},
  {number: 'Venezuela', region: '58'},
  {number: 'Vietnam', region: '84'},
  {number: 'Virgin Is.', region: '1809'},
  {number: 'Virgin Is. and St.Croix I.', region: '1809'},
  {number: 'Western sahara', region: '967'},
  {number: 'Wake I.', region: '1808'},
  {number: 'Wallis And Futuna Is.', region: '681'},
  {number: 'Yemen', region: '967'},
  {number: 'Yugoslavia', region: '381'},
  {number: 'Zimbabwe', region: '263'},
  {number: 'Zambia', region: '260'},
  {number: 'Zaire', region: '243'},
  {number: 'Zanzibar', region: '259'}
]
